
replicaCount: 1
domains:
  - name: archive.ngergs.de
    hsts:
      enabled: true
      preload: true
      subdomains: true
      max_age: "63072000"
volume:
  data:
    diskSize: 100G
    name: mayan-k8s-data # adjust as needed
  postgresql:
    diskSize: 10G
    name: mayan-k8s-postgresql # adjust as needed
imprint: "<html><head><title>Impressum</title></head><body><p><b>Impressum</b><br>Niklas Gergs<br>Redderbusch 55a<br>21698 Harsefeld<br>Email: admin (at) ngergs.de</p><p><b>Datenschutzerklärung</b><br>Beim Zugriff auf diese Webseiten werden die zugehörigen IP-Adressen gespeichert.<br>Die Log-Dateien werden ohne spezifischen Anlass nicht ausgewertet und nach 90 Tagen gelöscht.<br>Für den öffentlichen Berreichen werden keine weitergehenden benutzerbezogenen Daten erhoben, gespeichert oder ausgewertet.<br>Es werden keine Tracking-Cookies eingesetzt.</p></body></html>"

postgresql:
  password: #edit
  image:
    tag: 10
    pullPolicy: Always
  volumePermissions:
    enabled: true
  persistence:
    existingClaim: mayan-volume-postgresql # do not edit
    storageClass: mayan-storage # do not edit
    size: 100G
  existingSecret: mayan
  postgresqlDatabase: mayan # do not edit
  postgresqlUsername: mayan # do not edit

redis:
  password: #edit
  image:
    pullPolicy: Always
  architecture: standalone
  auth:
    existingSecret: mayan
    existingSecretPasswordKey: redis-password

