{{- range .Values.domains }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mayan-edms-{{ . }}
  annotations:
    nginx.org/mergeable-ingress-type: minion

spec:
  ingressClassName: nginx-kubeip
  rules:
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mayan-edms
            port:
              number: 8080
---
{{ end }}
