apiVersion: v1
kind: Secret
metadata:
  name: mayan
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password }}
  postgresql-password: {{ .Values.postgresql.password }}
  postgresql-postgres-password: {{ .Values.postgresql.password }}
  postgresql-replication-password: {{ .Values.postgresql.password }}
  postgresql-ldap-password: {{ .Values.postgresql.password }}
  celery-broker-url: "redis://:{{ .Values.redis.password }}@mayan-redis-master:6379/0"
  celery-result-backend: "redis://:{{ .Values.redis.password }}@mayan-redis-master:6379/1"
  databases: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'{{ .Values.postgresql.postgresqlDatabase }}','PASSWORD':'{{ .Values.postgresql.password }}','USER':'{{ .Values.postgresql.postgresqlUsername }}','HOST':'mayan-postgresql'}}"
  lock-manager-backend-arguments: "{'redis_url':'redis://:{{ .Values.redis.password }}@mayan-redis-master:6379/2'}"
