{{- if .Values.imprint -}}
apiVersion: v1
kind: Service
metadata:
  name: imprint
  labels:
    app.kubernetes.io/name: imprint
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: imprint
{{- end }}
