apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayan-storage-data
provisioner: kubernetes.io/glusterfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mayan-volume-data
spec:
  storageClassName: mayan-storage-data
  capacity:
    storage: {{ .Values.volume.data.diskSize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: mayan-volume-data
  gcePersistentDisk:
    pdName: {{ .Values.volume.data.name }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayan-volume-data
spec:
  storageClassName: mayan-storage-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.data.diskSize }} 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayan-storage-postgresql
provisioner: kubernetes.io/glusterfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mayan-volume-postgresql
spec:
  storageClassName: mayan-storage-postgresql
  capacity:
    storage: {{ .Values.volume.postgresql.diskSize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: mayan-volume-postgresql
  gcePersistentDisk:
    pdName: {{ .Values.volume.postgresql.name }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayan-volume-postgresql
spec:
  storageClassName: mayan-storage-postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.postgresql.diskSize }} 
